#!/bin/sh
#

RETVAL=0

KIND="DDNS"

DDNS_ENABLE=`grep "^ddns_enable=" /etc/default/config | cut -d = -f 2`

start() {
	if [ $DDNS_ENABLE -eq 1 ] ; then
		PID=$(pgrep -f "inadyn")
		if [ ${PID:-empty} = "empty" ] ; then
			echo "Starting $KIND service..."
			inadyn &
			sleep 1
		fi
	fi
}	

stop() {
	echo "Shutting down $KIND service..."
	pkill -9 -f "inadyn"
}	

restart() {
	stop
	sleep 1
	start
}

webstatus(){
	PID=$(pgrep -f "inadyn")
	if [ ${PID:-empty} = "empty" ] ; then
		echo -n "$KIND is not running"
    else
    	echo -n "$KIND is running"
    fi  		
}		

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  reload)
  	reload
	;;
  webstatus)
  	webstatus
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

