#!/bin/sh
#

KIND="WEBSERVER"

ENABLE=$(sed -n "s/^\(webserver_enable\)=\(.*\)$/\2/p" /etc/default/config)
PORT=$(sed -n "s/^\(webserver_port\)=\(.*\)$/\2/p" /etc/default/config)
ROOT=$(sed -n "s/^\(webserver_root\)=\(.*\)$/\2/p" /etc/default/config)

PARAM="-c /etc/webserver.conf -h ${ROOT}"

start() {
	if [ $ENABLE -eq 1 ] ; then
		PID=$(pgrep -f "httpd ${PARAM}")
		if [ ${PID:-empty} = "empty" ] ; then
			echo "Starting $KIND service..."
		    httpd ${PARAM} -p ${PORT} -r SNAKE
		fi
	fi
}

stop() {
	echo "Shutting down $KIND service..."
	pkill -9 -f "httpd ${PARAM}"
}

restart() {
	stop
	sleep 1
	start
}

webstatus(){
	PID=$(pgrep -f "httpd ${PARAM}")
	if [ ${PID:-empty} = "empty" ] ; then
		echo -n "$KIND is not running"
    else
    	echo -n "$KIND is running"
    fi  		
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  reload)
  	restart
	;;
  webstatus)
	webstatus
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac


